=== hongbofan/file-import-export/config/src/main/resources/config.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3school.com.cn"
           xmlns="http://www.w3school.com.cn"
           elementFormDefault="qualified">

    <xs:element name="configuration" >
        <xs:complexType>
            <xs:all>
                <xs:element name="txt" type="txtType" minOccurs="0"/>
                <xs:element name="csv" type="csvType" minOccurs="0"/>
                <xs:element name="excel" type="excelType" minOccurs="0"/>
                <xs:element name="mapper" type="mapperType" minOccurs="0"/>
            </xs:all>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="txtType">
        <xs:all>
            <xs:element name="separator" type="xs:string" default=" " minOccurs="0"/>
            <xs:element name="importFileCharset" type="xs:string" default="utf-8" minOccurs="0"/>
            <xs:element name="hasHeader" type="xs:boolean" default="false" minOccurs="0" />
            <xs:element name="skipBlankRow" type="xs:boolean" default="true" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="csvType">
        <xs:all>
            <xs:element name="separator" type="xs:string" default=" " minOccurs="0"/>
            <xs:element name="importFileCharset" type="xs:string" default="utf-8" minOccurs="0"/>
            <xs:element name="hasHeader" type="xs:boolean" default="false" minOccurs="0" />
            <xs:element name="skipBlankRow" type="xs:boolean" default="true" minOccurs="0"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="excelType">
        <xs:all>
            <xs:element name="separator" type="xs:string" default=" " minOccurs="0"/>
            <xs:element name="importFileCharset" type="xs:string" default="utf-8" minOccurs="0"/>
            <xs:element name="hasHeader" type="xs:boolean" default="false" minOccurs="0" />
            <xs:element name="skipBlankRow" type="xs:boolean" default="true" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="mapperType">
        <xs:sequence>
            <xs:element name="entity" type="entityType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="bean" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="entityType">
        <xs:attribute name="key" use="required"/>
        <xs:attribute name="value" use="required"/>
        <xs:attribute name="type" default="string"/>
    </xs:complexType>
</xs:schema>

=== hongbofan/file-import-export/config/src/main/resources/xxxx-config.xml
<?xml version="1.0"?>
<configuration
        xmlns="http://www.w3school.com.cn"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3school.com.cn config.xsd" id="config1">

    <mapper bean="com.flyread.file.imp0rt.base.Book">
        <entity key="题名" value="name" type="String"/>
        <entity key="ISBN" value="isbn" type="啊打发"/>
        <entity key="责任者" value="infoAuthor"/>
        <entity key="出版社" value="infoPublisher"/>
        <entity key="出版日期" value="infoPubdate"/>
        <entity key="单价" value="infoPrice"/>
        <entity key="已定数量" value="orderCount"/>
    </mapper>
</configuration>
